title: Captain Faulmann Blog
description: Exported posts
timezone: Europe/Berlin
url: ""   # set to https://<your-user>.github.io or https://<your-domain>
baseurl: "" # set if deploying to a subpath (e.g., /blog)
permalink: /:year/:month/:day/:title/
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag